name=ESPNetworkSerial
version=0.0.8
author=EudoksjuszSzalony
maintainer=EudoksjuszSzalony
sentence=Wireless Serial Monitor for ESP32, integrated directly with Arduino IDE.
paragraph=Use Wi-Fi for bidirectional serial communication with a simple Arduino API while keeping an OTA-friendly workflow.
category=Communication
url=https://github.com/EudoksjuszSzalony/ESPNetworkSerial
architectures=esp32
includes=ESPNetworkSerial.h
