[CmdletBinding()]
param(
    [Parameter(Mandatory = $true)]
    [ValidateSet("autogenerated_hmac_sha256", "password")]
    [string]$Mode,
    [Parameter(Mandatory = $true)]
    [string]$MonitorPath,
    [Parameter(Mandatory = $true)]
    [string]$RegisterScriptPath,
    [string]$ArduinoDataRoot = "",
    [switch]$Quiet
)

$ErrorActionPreference = "Stop"

try {
    $MonitorPath = [System.IO.Path]::GetFullPath($MonitorPath)
    $RegisterScriptPath = [System.IO.Path]::GetFullPath($RegisterScriptPath)

    if (-not (Test-Path -LiteralPath $MonitorPath -PathType Leaf)) {
        throw "Monitor executable not found: $MonitorPath"
    }
    if (-not (Test-Path -LiteralPath $RegisterScriptPath -PathType Leaf)) {
        throw "Registration script not found: $RegisterScriptPath"
    }

    $args = @(
        "-NoProfile",
        "-ExecutionPolicy", "Bypass",
        "-File", $RegisterScriptPath,
        "-MonitorPath", $MonitorPath,
        "-OtaMode", $Mode
    )
    if (-not [string]::IsNullOrWhiteSpace($ArduinoDataRoot)) {
        $args += @("-ArduinoDataRoot", $ArduinoDataRoot)
    }

    & powershell.exe @args
    $exitCode = $LASTEXITCODE
    if ($exitCode -ne 0 -and $exitCode -ne 2) {
        throw "Arduino integration update failed with exit code $exitCode."
    }

    Write-Host ""
    if ($Mode -eq "autogenerated_hmac_sha256") {
        Write-Host "OTA authentication mode: autogenerated HMAC-SHA256 key" -ForegroundColor Green
        Write-Host "Arduino IDE will upload without a password prompt."
    } else {
        Write-Host "OTA authentication mode: password" -ForegroundColor Green
        Write-Host "Arduino IDE will use the standard OTA password prompt."
    }
    Write-Host ""
    Write-Host "Restart Arduino IDE before the next network upload."

    if (-not $Quiet) {
        Write-Host ""
        Read-Host "Press Enter to close"
    }

    exit $exitCode
}
catch {
    Write-Error $_
    if (-not $Quiet) {
        Write-Host ""
        Read-Host "Press Enter to close"
    }
    exit 1
}
